import React, { createContext, useState, useContext, useEffect } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    homeim: "I'M",
    navbarHome: "Home",
    navbarAbout: "About",
    navbarProjects: "Projects",
    navbarResume: "Resume",
    navbarBlogs: "Blogs",
    homeGreeting: "Hi There!",
    homeNameTranslation: "Thon Bunleng",
    homeIntroPrefix: "LET ME",
    homeIntroMiddle: "INTRODUCE",
    homeIntroSuffix: "MYSELF",
    availableFreelance: "Available for Freelance",
    homeHeroTitle: "SOFTWARE",
    homeHeroTitleHighlight: "ENGINEER",
    homeHeroTagline: "Building Quality Software, Fast",
    homeImPrefix: "I'M",
    homeImName: "Thon Bunleng",
    homeIntroParagraph:
      "I'm a Software Engineer who loves transforming ideas into reliable, scalable products. Over time, I've explored several technologies and found my passion in building high-performance systems and intuitive user experiences.<br/><br/>I work across both frontend and backend stacks, with primary expertise in <span class=\"tech-flutter\">Flutter</span>, <span class=\"tech-react-native\">React Native</span>, <span class=\"tech-swift\">Swift</span>, <span class=\"tech-kotlin\">Kotlin</span>, <span class=\"tech-javascript\">JavaScript</span>, <span class=\"tech-laravel\">Laravel</span>, <span class=\"tech-nodejs\">Node.js</span>, and <span class=\"tech-python\">Python</span>.<br/><br/>My key areas of interest include Mobile & Web Applications, Blockchain Solutions, and exploring new ways to bridge on-chain and off-chain systems.",
    homeFindMe: "Find Me On",
    homeConnect: "Feel free to connect with me",
    homeConnectHighlight: "connect",
    contactPhone: "+855 011 820 595",
    contactEmail: "leng94570@gmail.com",
    telegramAriaLabel: "Open Telegram",
    telegramQrAlt: "Telegram QR code",
    telegramLabel: "Telegram",
    aboutTitlePrefix: "Know Who ",
    aboutTitleHighlight: "I'M",
    aboutTitleSuffix: "...!",
    aboutCardName: "THON BUNLENG",
    aboutCardCity: "Phnom Penh, Cambodia",
    aboutCardRole: "Software Developer",
    aboutCardParagraph:
      "Hi everyone! I'm Thon Bunleng from Phnom Penh, Cambodia. I'm a Software Developer passionate about building scalable mobile and web applications with clean architecture and modern tools.",
    aboutCardEducation: "Computer Science",
    aboutCardUniversity: "BELTEI International University",
    aboutCardActivitiesPrefix:
      "Outside of coding, I love engaging in activities that keep me creative and inspired",
    aboutCardActivities: {
      games: "Playing Games 🎮",
      blogs: "Writing Tech Blogs ✍️",
      travel: "Traveling and Exploring New Places 🌍",
    },
    aboutCardQuote: '"Strive to build things that make a difference!"',
    aboutCardFooter: "THON BUNLENG",
    professionalSkills: "Professional Skillset",
    toolsTitle: "Tools I use",
    toolsTitlePrefix: "Tools",
    toolsTitleSuffix: "I use",
    projectsTitlePrefix: "My",
    projectsTitleHighlight: "Recent",
    projectsTitleSuffix: "Works",
    projectsSubtitle: "Here are a few projects I've worked on recently.",
    resumeTitlePrefix: "My",
    resumeTitleHighlight: "Resume",
    resumeTitleSuffix: "",
    resumeSummary: "A summary of my professional journey, skills, and education.",
    resume: {
      experience: [
        {
          title: "Mobile App Developer (Flutter/Dart)",
          company: "Wintech Software Development Cambodia Co. Ltd",
          period: "2025 – 2026",
          details: [
            "Developed and maintained a complete Coffee Shop Management System (Wintech Software Development Cambodia Co. Ltd) as a production-ready mobile application.",
            "Built core features including POS, inventory management, sales reporting, and user authentication using Flutter/Dart.",
            "Collaborated with backend and QA teams to integrate APIs and ensure smooth deployment in a live business environment.",
          ],
        },
        {
          title: "Backend Developer Intern",
          company: "VANNA (Siem Reap, Cambodia)",
          period: "July 2024 – October 2024",
          details: [
            "Developed and maintained RESTful APIs using Node.js and Express, delivering reliable endpoints for mobile and web clients.",
            "Integrated MongoDB and PostgreSQL into backend services, improving data access speed by up to 30%.",
            "Collaborated with cross-functional teams to deliver features in sprints and participated in code reviews.",
          ],
        },
        {
          title: "Developer Freelancer & Open Source Contributor",
          company: "Freelance & Open Source",
          period: "2024 – Present",
          details: [
            "Built and deployed full-stack applications using Laravel, React, and Flutter for various clients.",
            "Contributed to open-source projects and created technical content (blogs and tutorials) for the developer community.",
            "Designed efficient SQL queries and REST APIs, reducing application response time by 25%.",
          ],
        },
        {
          title: "Designer & Video Editor",
          company: "Freelance",
          period: "2024 – Present",
          details: [
            "Provided freelance design and video editing services for clients, creating visual content for social media, branding, and marketing campaigns.",
            "Edited and produced high-quality videos using modern tools, improving client engagement and online presence.",
            "Collaborated with diverse teams to deliver creative solutions tailored to client needs.",
          ],
        },
      ],
      education: [
        {
          title: "Bachelor of Science in Computer Science",
          school: "Beltei International University (Phnom Penh, Cambodia)",
          period: "2023 – 2026",
          details: [
            "Focused on software engineering, algorithms, databases, and web/mobile technologies.",
            "Capstone project: Automated School Management System.",
          ],
        },
        {
          title: "High School Diploma – Social Sciences",
          school: "Preah Bat Samdech Preah Boromneath Norodom Sihamoni General and Technical High School",
          period: "2019 – 2023",
          details: [
            "Graduated with a focus on Social Sciences and mathematics, achieving top grades in computer science and physics.",
          ],
        },
      ],
      skills: [
        "Flutter / Dart",
        "JavaScript / TypeScript",
        "React.js / Next.js",
        "Node.js / Express",
        "Laravel / PHP",
        "MongoDB / PostgreSQL",
        "Docker / Git / CI-CD",
        "Tailwind CSS / Bootstrap",
      ],
      tools: [
        "VS Code",
        "Postman",
        "IntelliJ IDEA",
        "Android Studio",
        "Figma",
        "GitHub / GitLab",
        "Linux",
      ],
    },
    experienceTitle: "Experience",
    educationTitle: "Education",
    skillsTitle: "Skills",
    technicalSkillsTitle: "Technical",
    technicalSkillsHighlight: "Skills",
    technicalSkillsSubtitle: "Tools and technologies I work with on a daily basis.",
    githubButton: "GitHub",
    demoButton: "Demo",
    blogButton: "Blog",
    readArticle: "Read Article",
    backToBlogs: "Back to Blogs",
    blogTitle: "My Blogs",
    blogSubtitle:
      "Deep dives into mobile app architecture, UI/UX implementation, and clean code.",
    blogNotFound: "Blog not found",
    codeDays: "Days I Code",
    codeDaysHighlight: "Code",
    footerDesigned: "Designed and Developed by Thon Bunleng",
    footerCopyright: "Copyright ©",
    footerBy: "Thon Bunleng",
    languagePageTitle: "Choose Your Language",
    languagePageSubtitle: "Select a language to continue",
    languagePageEnglish: "English",
    languagePageKhmer: "Khmer",
    languagePageContinue: "Continue",
    typeOptions: {
      softwareDeveloper: "Software Developer",
      mobileAppDeveloper: "Mobile App Developer",
      webDeveloper: "Web Developer",
      uxUiDesigner: "UX/UI Designer",
      freelancer: "Freelancer",
      mernStackDeveloper: "MERN Stack Developer",
      openSourceContributor: "Open Source Contributor",
    },
    servicesTitle: "Services",
    services: {
      webDevelopment: "Web Development",
      mobileAppDevelopment: "Mobile App Development",
      customSoftwareDevelopment: "Custom Software Development",
      apiIntegration: "API Integration",
      databaseDesign: "Database Design",
      bugFixingMaintenance: "Bug Fixing & Maintenance",
      systemDevelopment: "System Development for Businesses",
    },
    socialLabels: {
      github: "GitHub",
      gitlab: "GitLab",
      linkedin: "LinkedIn",
      telegram: "Telegram",
      facebook: "Facebook",
      youtube: "YouTube",
      tiktok: "TikTok",
      phone: "Phone",
    },
    meWelcome: "Welcome to my portfolio",
    meHeroDescription:
      "Full-Stack & Mobile Application Developer crafting responsive web solutions, intuitive UI/UX designs, and scalable cross-platform mobile apps for iOS and Android.",
    meAvailableForHire: "Available for Hire",
    meSpecialist: "Web & Mobile Specialist",
    meHireMe: "Hire Me",
    meLearnMore: "Learn More",
    meGetInTouch: "Get in touch",
    meBrandName: "THON BUNLENG",
  },
  km: {
    navbarHome: "ទំព័រដើម",
    navbarAbout: "អំពីខ្ញុំ",
    navbarProjects: "គម្រោង",
    navbarResume: "ប្រវត្តិរូប",
    navbarBlogs: "អត្ថបទ",
    homeGreeting: "សួស្តី!",
    homeNameTranslation: "ថុន ប៊ុនឡេង",
    homeIntroPrefix: "ខ្ញុំចង់",
    homeIntroMiddle: "ណែនាំ",
    homeIntroSuffix: "ខ្លួនឯង",
    availableFreelance: "អាចទទួលការងារឯករាជ្យបាន",
    homeHeroTitle: "អ្នកអភិវឌ្ឍ",
    homeHeroTitleHighlight: "កម្មវិធី",
    homeHeroTagline: "សាងសង់កម្មវិធីដែលមានគុណភាព យ៉ាងមានទំនុកចិត្តនិងឆាប់រហ័ស",
    homeIntroParagraph:
      "ខ្ញុំជាវិស្វករកម្មវិធី (Software Engineer) ដែលមានចំណូលចិត្តក្នុងការផ្លាស់ប្តូរគំនិតច្នៃប្រឌិត ឱ្យទៅជាផលិតផលបច្ចេកវិទ្យាដែលមានប្រសិទ្ធភាព និងអាចពង្រីកមាត្រដ្ឋានបាន (Scalable)។ ខ្ញុំផ្តោតលើការបង្កើតប្រព័ន្ធដំណើរការល្បឿនលឿន ព្រមទាំងបទពិសោធន៍អ្នកប្រើប្រាស់ដ៏រលូន។<br/><br/>ខ្ញុំមានជំនាញ និងបទពិសោធន៍ក្នុងការធ្វើការទាំង Frontend និង Backend ដោយប្រើប្រាស់បច្ចេកវិទ្យាចម្បងៗដូចជា <span class=\"tech-flutter\">Flutter</span>, <span class=\"tech-laravel\">Laravel</span>, <span class=\"tech-nodejs\">Node.js</span>, <span class=\"tech-react-native\">React Native</span> និង <span class=\"tech-javascript\">JavaScript</span>។<br/><br/>គោលដៅចម្បងរបស់ខ្ញុំគឺការអភិវឌ្ឍ Mobile & Web Applications, ដំណោះស្រាយ Blockchain និងការភ្ជាប់ប្រព័ន្ធ on-chain ជាមួយ off-chain។",
    homeFindMe: "រកខ្ញុំនៅទីនេះ",
    homeim: "ខ្ញុំបាទឈ្មោះ",
    homeImPrefix: "ខ្ញុំបាទឈ្មោះ",
    homeImName: "ថុន ប៊ុនឡេង",
    homeConnect: "សូមទំនាក់ទំនងជាមួយខ្ញុំ",
    homeConnectHighlight: "ទំនាក់ទំនង",
    contactPhone: "+855 011 820 595",
    contactEmail: "leng94570@gmail.com",
    telegramAriaLabel: "បើក Telegram",
    telegramQrAlt: "កូដ QR Telegram",
    telegramLabel: "Telegram",
    aboutTitlePrefix: "ស្គាល់",
    aboutTitleHighlight: "ខ្ញុំ",
    aboutTitleSuffix: "...!",
    aboutCardName: "ថុន ប៊ុនឡេង",
    aboutCardCity: "រាជធានីភ្នំពេញ, ប្រទេសកម្ពុជា",
    aboutCardRole: "អ្នកអភិវឌ្ឍន៍កម្មវិធី",
    aboutCardParagraph:
      "សួស្តីអ្នកគ្រប់គ្នា! ខ្ញុំបាទឈ្មោះ <span class=\"purple\">ថុន ប៊ុនឡេង</span> មកពី <span class=\"purple\">រាជធានីភ្នំពេញ, ប្រទេសកម្ពុជា</span>។<br />ខ្ញុំជាអ្នកអភិវឌ្ឍន៍កម្មវិធីដែលមានចំណង់ចំណូលចិត្តក្នុងការបង្កើតកម្មវិធីទូរស័ព្ទ និងវេបសាយដែលអាចពង្រីកបាន ដែលមានស្ថាបត្យកម្មស្អាត និងឧបករណ៍ទំនើប។",
    aboutCardEducation: "វិទ្យាសាស្ត្រកុំព្យូទ័រ",
    aboutCardUniversity: "សាកលវិទ្យាល័យអន្តរជាតិ ប៊ែលធី",
    aboutCardActivitiesPrefix:
      "ក្រៅពីការសរសេរកូដ ខ្ញុំស្រឡាញ់ធ្វើសកម្មភាពដែលធ្វើឱ្យខ្ញុំមានភាពច្នៃប្រឌិត និងទទួលការបំផុសគំនិត៖",
    aboutCardActivities: {
      games: "លេងហ្គេម 🎮",
      blogs: "សរសេរប្លុកបច្ចេកវិទ្យា ✍️",
      travel: "ធ្វើដំណើរនិងរុករកទីកន្លែងថ្មីៗ 🌍",
    },
    aboutCardQuote: '"ខិតខំបង្កើតអ្វីៗដែលបង្កើតការផ្លាស់ប្តូរ!"',
    aboutCardFooter: "ថុន ប៊ុនឡេង",
    professionalSkills: "ជំនាញវិជ្ជាជីវៈ",
    toolsTitle: "ឧបករណ៍ដែលខ្ញុំប្រើ",
    toolsTitlePrefix: "ឧបករណ៍",
    toolsTitleSuffix: "ដែលខ្ញុំប្រើ",
    projectsTitlePrefix: "គម្រោង",
    projectsTitleHighlight: "ថ្មីៗ",
    projectsTitleSuffix: "របស់ខ្ញុំ",
    projectsSubtitle: "នេះជាគម្រោងខ្លះដែលខ្ញុំបានធ្វើថ្មីៗនេះ។",
    resumeTitlePrefix: "ប្រវត្តិរូប",
    resumeTitleHighlight: "សង្ខេប",
    resumeTitleSuffix: "របស់ខ្ញុំ",
    resumeSummary: "សេចក្តីសង្ខេបនៃដំណើរវិជ្ជាជីវៈ ជំនាញ និងការសិក្សារបស់ខ្ញុំ។",
    resume: {
      experience: [
        {
          title: "អ្នកអភិវឌ្ឍន៍កម្មវិធីទូរស័ព្ទ (Flutter/Dart)",
          company: "Wintech Software Development Cambodia Co. Ltd",
          period: "2025 – 2026",
          details: [
            "អភិវឌ្ឍន៍និងថែរក្សាប្រព័ន្ធគ្រប់គ្រងហាងកាហ្វេជាកម្មវិធីទូរស័ព្ទដែលរួចរាល់សម្រាប់ប្រើការ។",
            "បង្កើតមុខងារដូចជា POS ការគ្រប់គ្រងស្តុក របាយការណ៍លក់ និងការផ្ទៀងផ្ទាត់អ្នកប្រើប្រាស់ ដោយប្រើ Flutter/Dart។",
            "សហការជាមួយក្រុម Backend និង QA ដើម្បីភ្ជាប់ API និងធានាការដំណើរការរលូននៅក្នុងបរិយាកាសធ្វើការពិតប្រាកដ។",
          ],
        },
        {
          title: "អ្នកអភិវឌ្ឍន៍ Backend ក្រោមការបណ្តុះបណ្តាល",
          company: "VANNA (សៀមរាប, កម្ពុជា)",
          period: "កក្កដា 2024 – តុលា 2024",
          details: [
            "អភិវឌ្ឍន៍និងថែរក្សា RESTful APIs ដោយប្រើ Node.js និង Express ផ្តល់ endpoint ដែលអាចជឿទុកចិត្តបានសម្រាប់កម្មវិធីទូរស័ព្ទ និងវេបសាយ។",
            "ដាក់បញ្ចូល MongoDB និង PostgreSQL ទៅក្នុងសេវាកម្ម Backend ធ្វើឲ្យល្បឿនចូលដំណើរទិន្នន័យកើនឡើងដល់ ៣០%។",
            "សហការជាមួយក្រុមមុខងារផ្សេងៗ ដើម្បីដំណើរការផ្ដល់ feature នៅក្នុង sprint និងចូលរួមក្នុងការត្រួតពិនិត្យកូដ។",
          ],
        },
        {
          title: "អ្នកអភិវឌ្ឍន៍ឯករាជ្យ & អ្នករួមចំណែក Open Source",
          company: "Freelance & Open Source",
          period: "2024 – បច្ចុប្បន្ន",
          details: [
            "បង្កើតនិងដំណើរការកម្មវិធី Full-Stack ដោយប្រើ Laravel, React, និង Flutter សម្រាប់អតិថិជនជាច្រើន។",
            "រួមចំណែកនៅក្នុងគម្រោង Open Source និងបង្កើតមាតិកាបច្ចេកទេស (ប្លុក និង tutorial) សម្រាប់សហគមន៍អ្នកអភិវឌ្ឍន៍។",
            "រចនាសំណួរ SQL និង REST API ដែលមានប្រសិទ្ធភាព ធ្វើឲ្យពេលវេលាឆ្លើយតបនៃកម្មវិធីប្រសើរឡើង ២៥%។",
          ],
        },
      ],
      education: [
        {
          title: "បរិញ្ញាបត្រវិទ្យាសាស្ត្រកុំព្យូទ័រ",
          school: "សាកលវិទ្យាល័យអន្តរជាតិ ប៊ែលធី (ភ្នំពេញ, កម្ពុជា)",
          period: "២០២៣ – ២០២៦",
          details: [
            "ផ្តោតលើវិស្វកម្មសូហ្វវែរ ក្បួនដោះស្រាយ មូលដ្ឋានទិន្នន័យ និងបច្ចេកវិទ្យាវេបសាយ/ទូរស័ព្ទ។",
            "គម្រោងចប់ស្រេច: ប្រព័ន្ធគ្រប់គ្រងសាលារៀនស្វ័យប្រវត្តិ។",
          ],
        },
        {
          title: "សញ្ញាបត្រវិទ្យាល័យ – ផ្នែកវិទ្យាសាស្ត្រសង្គម",
          school: "វិទ្យាល័យចំណេះទូទៅនិងបច្ចេកទេស ព្រះបាទសម្ដេចព្រះបរមនាថ នរោត្ដម សីហមុនី",
          period: "២០១៩ – ២០២៣",
          details: [
            "បញ្ចប់ការសិក្សាដោយផ្តោតលើវិទ្យាសាស្ត្រសង្គម និងគណិតវិទ្យា ទទួលបានពិន្ទុខ្ពស់ក្នុងវិទ្យាសាស្ត្រកុំព្យូទ័រ និងរូបវិទ្យា។",
          ],
        },
      ],
      skills: [
        "Flutter / Dart",
        "JavaScript / TypeScript",
        "React.js / Next.js",
        "Node.js / Express",
        "Laravel / PHP",
        "MongoDB / PostgreSQL",
        "Docker / Git / CI-CD",
        "Tailwind CSS / Bootstrap",
      ],
      tools: [
        "VS Code",
        "Postman",
        "IntelliJ IDEA",
        "Android Studio",
        "Figma",
        "GitHub / GitLab",
        "Linux",
      ],
    },
    experienceTitle: "បទពិសោធន៍",
    educationTitle: "ការសិក្សា",
    skillsTitle: "ជំនាញ",
    technicalSkillsTitle: "បច្ចេកទេស",
    technicalSkillsHighlight: "ជំនាញ",
    technicalSkillsSubtitle: "ឧបករណ៍និងបច្ចេកវិទ្យាដែលខ្ញុំប្រើប្រចាំថ្ងៃ។",
    githubButton: "GitHub",
    demoButton: "សាកល្បង",
    blogButton: "អត្ថបទ",
    readArticle: "អានអត្ថបទ",
    backToBlogs: "ត្រឡប់ទៅអត្ថបទ",
    blogTitle: "អត្ថបទរបស់ខ្ញុំ",
    blogSubtitle:
      "ការស្វែងយល់ស៊ីជម្រៅអំពីស្ថាបត្យកម្មកម្មវិធីទូរស័ព្ទ ការអនុវត្ត UI/UX និងការសរសេរកូដស្អាត។",
    blogNotFound: "រកមិនឃើញអត្ថបទ",
    codeDays: "ថ្ងៃដែលខ្ញុំសរសេរ",
    codeDaysHighlight: "កូដ",
    footerDesigned: "រចនានិងអភិវឌ្ឍដោយ ថុន ប៊ុនឡេង",
    footerCopyright: "រក្សាសិទ្ធ ©",
    footerBy: "ថុន ប៊ុនឡេង",
    languagePageTitle: "ជ្រើសរើសភាសារបស់អ្នក",
    languagePageSubtitle: "ជ្រើសរើសភាសាមួយដើម្បីបន្ត",
    languagePageEnglish: "English",
    languagePageKhmer: "ខ្មែរ",
    languagePageContinue: "បន្ត",
    typeOptions: {
      softwareDeveloper: "អ្នកអភិវឌ្ឍន៍កម្មវិធី",
      mobileAppDeveloper: "អ្នកអភិវឌ្ឍន៍កម្មវិធីទូរស័ព្ទ",
      webDeveloper: "អ្នកអភិវឌ្ឍន៍វេបសាយ",
      uxUiDesigner: "អ្នករចនា UX/UI",
      freelancer: "អ្នកធ្វើការឯករាជ្យ",
      mernStackDeveloper: "អ្នកអភិវឌ្ឍន៍ MERN Stack",
      openSourceContributor: "អ្នករួមចំណែក Open Source",
    },
    servicesTitle: "សេវាកម្ម",
    services: {
      webDevelopment: "អភិវឌ្ឍន៍វេបសាយ",
      mobileAppDevelopment: "អភិវឌ្ឍន៍កម្មវិធីទូរស័ព្ទ",
      customSoftwareDevelopment: "អភិវឌ្ឍន៍កម្មវិធីផ្ទាល់ខ្លួន",
      apiIntegration: "ការរួមបញ្ចូល API",
      databaseDesign: "ការរចនាមូលដ្ឋានទិន្នន័យ",
      bugFixingMaintenance: "ការជួសជុល និង ថែរក្សា",
      systemDevelopment: "អភិវឌ្ឍន៍ប្រព័ន្ធសម្រាប់អាជីវកម្ម",
    },
    socialLabels: {
      github: "GitHub",
      gitlab: "GitLab",
      linkedin: "LinkedIn",
      telegram: "Telegram",
      facebook: "Facebook",
      youtube: "YouTube",
      tiktok: "TikTok",
      phone: "ទូរស័ព្ទ",
    },
    meWelcome: "សួស្តីមកកាន់បណ្តាញខ្ញុំ",
    meHeroDescription:
      "អ្នកអភិវឌ្ឍន៍ Full-Stack & Mobile Application ដែលបង្កើតឧបករណ៍វេបសាយដែលឆ្លើយតប, រចនាបថ UI/UX ដែលងាយប្រើ, និងកម្មវិធីទូរស័ព្ទដែលអាចពង្រីកបានសម្រាប់ iOS និង Android ។",
    meAvailableForHire: "មានលក់ដល់ពេលនេះ",
    meSpecialist: "ជំនាញ Web & Mobile",
    meHireMe: "ជួលខ្ញុំ",
    meLearnMore: "ស្វែងយល់បន្ថែម",
    meGetInTouch: "ទាក់ទងជាមួយខ្ញុំ",
    meBrandName: "ថុន ប៊ុនឡេង",
  },
zh: {
    homeim: "我是",
    navbarHome: "首頁",
    navbarAbout: "關於我",
    navbarProjects: "專案",
    navbarResume: "履歷",
    navbarBlogs: "部落格",
    homeGreeting: "你好！",
    homeNameTranslation: "何文霖",
    homeIntroPrefix: "讓",
    homeIntroMiddle: "我介紹",
    homeIntroSuffix: "自己",
    availableFreelance: "接案中",
    homeHeroTitle: "軟體",
    homeHeroTitleHighlight: "工程師",
    homeHeroTagline: "快速打造高品質軟體",
    homeImPrefix: "我是",
    homeImName: "何文霖",
    homeIntroParagraph:
      "我是一名熱愛將創意轉化為可靠、可擴充產品的軟體工程師。多年來，我探索了多種技術，並在打造高效能系統與直覺化使用者體驗中找到我的熱情。我精通 <span class=\"tech-flutter\">Flutter</span>、<span class=\"tech-react-native\">React Native</span>、<span class=\"tech-swift\">Swift</span>、<span class=\"tech-kotlin\">Kotlin</span>、<span class=\"tech-javascript\">JavaScript</span>、<span class=\"tech-cpp\">C++</span>、<span class=\"tech-csharp\">C#</span>、<span class=\"tech-rust\">Rust</span>、<span class=\"tech-nodejs\">Node.js</span>、<span class=\"tech-laravel\">Laravel</span>、<span class=\"tech-python\">Python</span> 和 <span class=\"tech-java\">Java</span> — 我喜歡在後端與前端的技術堆疊中工作。我的主要興趣領域包括開發行動應用程式與網頁應用程式、區塊鏈解決方案，以及探索連接鏈上與鏈下系統的新方法。只要有可能，我喜歡使用 Flutter 和現代框架如 <span class=\"tech-reactjs\">React.js</span> 和 <span class=\"tech-nextjs\">Next.js</span> 來打造專案。",
    homeFindMe: "找到我",
    homeConnect: "歡迎與我聯絡",
    homeConnectHighlight: "聯絡",
    contactPhone: "+855 011 820 595",
    contactEmail: "leng94570@gmail.com",
    telegramAriaLabel: "開啟 Telegram",
    telegramQrAlt: "Telegram 二維碼",
    telegramLabel: "Telegram",
    aboutTitlePrefix: "了解",
    aboutTitleHighlight: "我",
    aboutTitleSuffix: "...！",
    aboutCardName: "何文霖",
    aboutCardCity: "柬埔寨金邊",
    aboutCardRole: "軟體開發人員",
    aboutCardParagraph:
      "大家好！我是何文霖，來自柬埔寨金邊。我是一名充滿熱情的軟體開發人員，致力於使用簡潔架構與現代工具打造可擴充的行動與網頁應用程式。",
    aboutCardEducation: "電腦科學",
    aboutCardUniversity: "BELTEI國際大學",
    aboutCardActivitiesPrefix:
      "除了寫程式，我喜歡做一些能讓我保持創造力與靈感的活動",
    aboutCardActivities: {
      games: "玩遊戲 🎮",
      blogs: "寫技術部落格 ✍️",
      travel: "旅行與探索新地方 🌍",
    },
    aboutCardQuote: "努力創造有價值的事物！",
    aboutCardFooter: "THON BUNLENG",
    professionalSkills: "專業技能",
    toolsTitle: "我使用的工具",
    toolsTitlePrefix: "我使用的",
    toolsTitleSuffix: "工具",
    projectsTitlePrefix: "我的",
    projectsTitleHighlight: "近期",
    projectsTitleSuffix: "作品",
    projectsSubtitle: "以下是我最近完成的一些專案。",
    resumeTitlePrefix: "我的",
    resumeTitleHighlight: "履歷",
    resumeTitleSuffix: "",
    resumeSummary: "我的職涯歷程、技能與教育背景概覽。",
    resume: {
      experience: [
        {
          title: "行動應用程式開發工程師（Flutter/Dart）",
          company: "Wintech Software Development Cambodia Co. Ltd",
          period: "2025 – 2026",
          details: [
            "為 Wintech Software Development Cambodia Co. Ltd 開發並維護一套完整的咖啡店管理系統（行動應用程式）。",
            "使用 Flutter/Dart 建置核心功能，包括 POS、庫存管理、銷售報表與使用者驗證。",
            "與後端及 QA 團隊合作，整合 API，並確保在實際商業環境中順利部署。",
          ],
        },
        {
          title: "後端開發實習生",
          company: "VANNA（暹粒，柬埔寨）",
          period: "2024年7月 – 2024年10月",
          details: [
            "使用 Node.js 與 Express 開發並維護 RESTful API，為行動裝置與網頁用戶端提供穩定的端點。",
            "將 MongoDB 與 PostgreSQL 整合進後端服務，將資料存取速度提升 30%。",
            "與跨職能團隊合作，於衝刺（Sprint）中交付功能並參與程式碼審查。",
          ],
        },
        {
          title: "自由接案開發者與開源貢獻者",
          company: "自由接案與開源",
          period: "2024年 – 至今",
          details: [
            "使用 Laravel、React 與 Flutter 為各種客戶建置並部署全端應用程式。",
            "為開源專案做出貢獻，並為開發者社群創作技術內容（部落格與教學文章）。",
            "設計高效率的 SQL 查詢與 REST API，將應用程式回應時間縮短 25%。",
          ],
        },
        {
          title: "設計師與影片剪輯師",
          company: "自由接案",
          period: "2024年 – 至今",
          details: [
            "為客戶提供自由接案設計與影片剪輯服務，為社群媒體、品牌與行銷活動創作視覺內容。",
            "使用現代工具剪輯與製作高品質影片，提升客戶參與度與線上形象。",
            "與多元團隊合作，提供量身打造的創意解決方案以滿足客戶需求。",
          ],
        },
      ],
      education: [
        {
          title: "電腦科學學士",
          school: "BELTEI國際大學（柬埔寨金邊）",
          period: "2023年 – 2026年",
          details: [
            "專注於軟體工程、演算法、資料庫與網頁／行動技術。",
            "畢業專題：自動化學校管理系統。",
          ],
        },
        {
          title: "高中文憑 – 社會科學",
          school: "諾羅敦・西哈莫尼國王綜合技術高中",
          period: "2019年 – 2023年",
          details: [
            "以社會科學與數學為主修畢業，在電腦科學與物理方面表現優異。",
          ],
        },
      ],
      skills: [
        "Flutter / Dart",
        "JavaScript / TypeScript",
        "React.js / Next.js",
        "Node.js / Express",
        "Laravel / PHP",
        "MongoDB / PostgreSQL",
        "Docker / Git / CI-CD",
        "Tailwind CSS / Bootstrap",
      ],
      tools: [
        "VS Code",
        "Postman",
        "IntelliJ IDEA",
        "Android Studio",
        "Figma",
        "GitHub / GitLab",
        "Linux",
      ],
    },
    experienceTitle: "工作經歷",
    educationTitle: "教育背景",
    skillsTitle: "技能",
    technicalSkillsTitle: "技術",
    technicalSkillsHighlight: "技能",
    technicalSkillsSubtitle: "我日常使用的工具與技術。",
    githubButton: "GitHub",
    demoButton: "展示",
    blogButton: "部落格",
    readArticle: "閱讀文章",
    backToBlogs: "返回部落格",
    blogTitle: "我的部落格",
    blogSubtitle:
      "深入探討行動應用程式架構、UI/UX 實作與簡潔程式碼。",
    blogNotFound: "找不到部落格文章",
    codeDays: "寫程式天數",
    codeDaysHighlight: "程式碼",
    footerDesigned: "由何文霖設計開發",
    footerCopyright: "版權所有 ©",
    footerBy: "何文霖",
    languagePageTitle: "選擇您的語言",
    languagePageSubtitle: "選擇一種語言以繼續",
    languagePageEnglish: "英文",
    languagePageKhmer: "高棉語",
    languagePageContinue: "繼續",
    typeOptions: {
      softwareDeveloper: "軟體開發人員",
      mobileAppDeveloper: "行動應用程式開發人員",
      webDeveloper: "網頁開發人員",
      uxUiDesigner: "UX/UI 設計師",
      freelancer: "自由接案者",
      mernStackDeveloper: "MERN 全端開發人員",
      openSourceContributor: "開源貢獻者",
    },
    servicesTitle: "服務",
    services: {
      webDevelopment: "網頁開發",
      mobileAppDevelopment: "行動應用程式開發",
      customSoftwareDevelopment: "客製化軟體開發",
      apiIntegration: "API 整合",
      databaseDesign: "資料庫設計",
      bugFixingMaintenance: "錯誤修復與維護",
      systemDevelopment: "企業系統開發",
    },
    socialLabels: {
      github: "GitHub",
      gitlab: "GitLab",
      linkedin: "LinkedIn",
      telegram: "Telegram",
      facebook: "Facebook",
      youtube: "YouTube",
      tiktok: "TikTok",
      phone: "電話",
    },
    meWelcome: "歡迎來到我的作品集",
    meHeroDescription:
      "全端與行動應用程式開發人員，打造響應式網頁解決方案、直觀的 UI/UX 設計，以及適用於 iOS 和 Android 的可擴展跨平台行動應用程式。",
    meAvailableForHire: "誠徵中",
    meSpecialist: "網頁與行動專員",
    meHireMe: "僱用我",
    meLearnMore: "了解更多",
    meGetInTouch: "與我聯繫",
    meBrandName: "何文霖",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return typeof window !== "undefined" ? localStorage.getItem("language") || "en" : "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key) => {
    const keys = key.split(".");
    let value = translations[language];
    for (const k of keys) {
      if (value && typeof value === "object") {
        value = value[k];
      }
    }
    return value !== undefined && value !== null ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

export default LanguageContext;